### ISSUE TITLE
OrangeScrum not working after installation and configurations.

### ISSUE THREAD

**Issue by kisanme** [Orangescrum/orangescrum#102]
Hi there, 
I've set up OrangeScrum in my Ubuntu machine locally. I've also imported the database and added the email and database configurations to the configuration files as mentioned in the installation guide. But i see broken images and when i try to sign up i see 404 status in the network tab (in developer tools).

I'm sure all the prerequisites are met.

![screenshot from 2015-09-14 22-34-04](https://cloud.githubusercontent.com/assets/4737217/9856174/c59e3b8e-5b30-11e5-982b-b2aa36459989.png)

**Comment by Prabhudas** [comment]
Hi kisanme,

It seems that you might not set the "SUB_FOLDER" name in the constants.php.

i.e define('SUB_FOLDER', 'Your sub folder name goes here'); 

If you have already set the SUB_FOLDER, then please check .htaccess is working or not.

If you face any more issue then let us know.

**Comment by kisanme** [comment]
I don't have a subfolder, my sub-domain directly directs to the orangescrum directory. I'm also suspecting about the .htaccess file issue. Thanks for your help.

**Comment by kisanme** [comment]
I confirm the issue was with .htaccess, but now i get a 500 internal server error when i go to the sub-domain which is directed to my orangescrum.

**Comment by kisanme** [comment]
Directed to https://github.com/Orangescrum/orangescrum/issues/77

**Comment by pedropinto92** [comment]
hi,

Can you solve your problem? I have the same problem as you

**Comment by mohanarajnice** [comment]
Hi kisanme,
I have the same problem as you mentioned and i found that, the issue was happened in .htaccess file in root path. Now i have fixed that issue. Kindly copy and paste the below mentioned code in your .htaccess file in root path.

<IfModule mod_rewrite.c>
   Options +FollowSymLinks
   RewriteEngine on
   RewriteRule    ^$ app/webroot/    [L]
   RewriteRule    (.*) app/webroot/$1 [L]
</IfModule>

**Comment by bruccegrs** [comment]
Hi!

I have same problem here... 

- Php 5.6
- Mysql 5.6.26
- curl activated
- My .htaccess below:
<IfModule mod_rewrite.c>
   RewriteEngine on
   RewriteRule    (.*) app/webroot/$1 [L]
   Options +FollowSymLinks RewriteEngine on RewriteRule ^$ app/webroot/ [L] 
</IfModule>

I have tried a few solutions (changing .htaccess, with sub_folder, without sub_folder, checking all php/apache settings , but none works... 

Someone can solve this?

![captura de tela de 2018-07-26 08-24-49](https://user-images.githubusercontent.com/41738673/43259677-6948148a-90ad-11e8-9975-37d7442d9115.png)

**Comment by RaylightGames** [comment]
here same problem, any hints? thanks

**Comment by ashok83** [comment]
HI,

Please check on the constant.php file if it is empty. I noticed that there certain cronjob running which deleting the content of the constant.php file which causing the issue.

regards,
ashok
