### ISSUE TITLE
Field "logo" doesn't have any default values error when creating company

### ISSUE THREAD

**Issue by 101arg101** [Orangescrum/orangescrum#112]
I'm getting this error. You should allow more null values in your database.
{
  "errorInfo": ["HY000",1364,"Field 'logo' doesn't have a default value"],
  "queryString":"INSERT INTO `orangescrum`.`companies` (`uniq_id`, `seo_url`, `subscription_id`, `name`, `contact_phone`, `modified`, `created`) VALUES ('195d077bccc5e9bf29ef48eb617d6c91', '', 1, 'asdf', 'NA', '2016-02-25 22:25:46', '2016-02-25 22:25:46')"
}

**Comment by programster** [comment]
Whilst forking orangescrum into [scrumptious](https://github.com/programster/SCRUMptious/tree/programster) that focuses on ease of deploying through docker, I ran into tonnes of these issues. Then it clicked that the developers must have been using MySQL in [loose mode](http://blog.programster.org/mysql-prevent-defaulting-to-defaults/) which resulted in queries working even when not specifying the value for a column that is set to not null. One day it would be great to fix the queries and the database structure, but for now you can either just [deploy scrumptious through docker](https://www.youtube.com/watch?v=7yfb4ojcswo), or change your database's `sql_mode` variable.

**Comment by sarojksingh** [comment]
It is fixed in the code. Required changes made in the controller and database.sql file. Please let us know if you still face such problem.

**Comment by 101arg101** [comment]
No, I've stopped working with orangescrum. I can't format the php code automatically, and it's just too hard for me to read. I'm looking for open source software because I want to be able to edit it.
