### ISSUE TITLE
Problem in sending mails.

### ISSUE THREAD

**Issue by abhiskaushik** [Orangescrum/orangescrum#114]
When i add a user and send him invitation, the bootstrap modal says: `Invitation sent successfully` 
However, the mail is not delivered to the users.
I use ubuntu 14.04 and php_openssl is enabled by default in my opinion. I have also completed the suggested changes in config/Constants.php file.

Please help! Thanks!

**Comment by abhiskaushik** [comment]
![screenshot from 2016-03-07 18 34 46](https://cloud.githubusercontent.com/assets/4478973/13570253/5a3df7ca-e493-11e5-8572-81c8e799ded7.png)

My phpinfo() shows by default support for openssl.

**Comment by kitkatneko** [comment]
what did localhost/cron/test_email/?to=email@address.com says?

**Comment by abhiskaushik** [comment]
@kitkatneko   Thanks for getting back on it. I am really stuck with the issue. On my remove server i get this error. Want to fix it.  You can try it out [here](http://wecreateproblems.com/tracker/cron/test_email/?to=kabhi2104@gmail.com)

php_openssl in php.ini is enabled 

`ssl://smtp.gmail.com:465 is not responding`.



Simple Email Caught exception: Connection refused

Template Email Caught exception: Connection refused

**Comment by risendev** [comment]
It looks like gmail is recognizing Orangescrum mail as coming from a "Less Secure" app.  Here is more information on how you could change the account to allow it to send (https://support.google.com/accounts/answer/6010255).  Personally, I would rather figure out a method for to make it meet the security standards rather than lower the security on my account.

**Comment by abhiskaushik** [comment]
@risendev  yeah i resolved the issue with the same suggestions a month back. I was yet to update and close this. Sorry for that. Thank you.

**Comment by risendev** [comment]
@abhiskaushik No worries.  Thanks for the follow-up.

**Comment by cyberformed** [comment]
localhost/cron/test_email/?to=email@address.com says 

Please check you database connection in `app/Config/database.php` or may be some syntax error in your code

**Comment by glsysco** [comment]
Hey Guys,

I have the less secure app on and I'm getting the following error:

php_openssl in php.ini is enabled 
ssl://smtp.gmail.com:465: is not responding.
Simple Email Caught exception: Permission denied
Template Email Caught exception: Permission denied

It doesn't matter if I have less secure app enable or not.I receive the same error.

Thank you

**Comment by nravikanth** [comment]
Hi @glsysco 
Have you found solution for this ?, Even I am facing same issue.
