### ISSUE TITLE
Broken images Upon Install

### ISSUE THREAD

**Issue by brandinarsenault** [Orangescrum/orangescrum#159]
Hi there,

I installed orangescrum on my cPanel-based server subdomain of "elvis", which pulls from folder "public_html/elvis", so I am not defining a subfolder since it is at the root of the subdomain. 

However, when I visit the page, all the images are broken and it does not allow me to signup. See below:
![image](https://cloud.githubusercontent.com/assets/15201621/21288263/c5c846ac-c454-11e6-994f-6d43a68352f7.png)

Any help would be super appreciated!

**Comment by akmount** [comment]
Were you able to resolve this?

**Comment by WeskeRo** [comment]
I have same problem, Dont know if tis is broken server config or what .

**Comment by ChristianHpf** [comment]
Had the same issue.

**Comment by Prabhudas** [comment]
Hello,
we are sorry for the inconvenience caused.
Can you please share us the following information:
Operating System.
PHP version.
MySql version.
Server- XAMPP, WAMP, Apache etc
with us? We will review your error for further troubleshooting and respond with the next steps.

Best Regards
Team Orangescrum

**Comment by bruccegrs** [comment]
Hi!

I have same problem here...

    Php 5.6
    Mysql 5.6.26
    curl activated
    My .htaccess below:

RewriteEngine on RewriteRule (.*) app/webroot/$1 [L] Options +FollowSymLinks RewriteEngine on RewriteRule ^$ app/webroot/ [L]

I have tried a few solutions (changing .htaccess, with sub_folder, without sub_folder, checking all php/apache settings , but none works...

Someone can solve this?
![captura de tela de 2018-07-26 08-24-49](https://user-images.githubusercontent.com/41738673/43259928-495f74b4-90ae-11e8-9d7c-b0dbf81f1014.png)
