### ISSUE TITLE
[New feature] Display uploaded file size at task details popup

### ISSUE THREAD

**Issue by phong-et** [Orangescrum/orangescrum#2]
Hi team, my company has used **Orangescrum** for tasks management since 3 years, we recognize that if this feature is added, it will give user a better experience(at least for our company).
You could add optional setting to display size and name of uploaded files together.
Example : https://prnt.sc/dYHoyxl7v2qn

**Comment by amitanirudha** [comment]
Hi @phong-et, thank you for your suggestion. We have noted it. We will keep you posted.

**Comment by ajit-orangescrum** [comment]
Hey @phong-et, we are glad to inform the requested feature has been [released](https://github.com/Orangescrum/orangescrum/releases/tag/V2.0.3) for the SaaS and Community edition.

**Comment by phong-et** [comment]
Thanks Team, very much appreciated!
