### ISSUE TITLE
[help wanted] Running orangescrum on localhost. Permission error for the dashboard

### ISSUE THREAD

**Issue by nayabbashasayed** [Orangescrum/orangescrum#200]
Hi,
I am using Orangescrum on Ubuntu 16.04 localhost. I have installed the orangescrum and when I created the fist task, it redirected to my dashboard page. But I couldn't access any pages after that step. I am always getting the same error.

> The page you requested was not found
> --
> You may have clicked an expired link or mistyped the address.Some web addresses are case sensitive.
> 
Is there anything wrong with my installation?

**Comment by princessjohn** [comment]
can check your constant.php in app/config if it is having any content?

**Comment by nayabbashasayed** [comment]
This looks like most common problem. app/config/constant.php is getting
cleared. There should be some fix already.

**Comment by princessjohn** [comment]
I am using a shared server, what I did is to change the password of my server. then it worked for three days now without any problem.
