### ISSUE TITLE
Cannot post to existing task (TypeError in dashboard.js:589)

### ISSUE THREAD

**Issue by slorenco** [Orangescrum/orangescrum#212]
Hi,

After creating a new task and opening the task to post a progress change (New --> In-Progress) by clicking the green Post button, the following error occurs in my browser:

Uncaught TypeError: Cannot read property 'getContent' of undefined
    at validateComments (dashboard.js:589)
    at HTMLButtonElement.onclick (VM1197 54d9e25fdc1deae575eb827252c6027d:1)
validateComments @ dashboard.js:589
onclick @ VM1197 54d9e25fdc1deae575eb827252c6027d:1

**Comment by orangescrum1** [comment]
Hi @slorenco,

Thank you for letting us know. The issue has been fixed. Please download the latest version of the code from [here](https://www.orangescrum.org/free-download/?refer=b&utm_expid=.YT_TN7HOQxGrE6yGowbULQ.1&utm_referrer=https%3A%2F%2Fwww.orangescrum.org%2F)

Thanks,
Orangescrum Team

**Comment by slorenco** [comment]
Great!

That fixed it and working now.

Thanks
