### ISSUE TITLE
Time-log link not working from Dashboard page

### ISSUE THREAD

**Issue by andola-kalyani** [Orangescrum/orangescrum#4]
While using Orangescrum we come across an issue in dashboard Page. From here we are not able to open Time-log page. Could you please look into this.

**Comment by ajit-orangescrum** [comment]
Hey @andola-kalyani, we are glad to inform the detected issue has been fixed with the release of [V2.0.7](https://github.com/Orangescrum/orangescrum/releases/tag/V2.0.7).
