### ISSUE TITLE
Sorry, s3_error  file type is not allowed!

### ISSUE THREAD

**Issue by karanveersingh001** [Orangescrum/orangescrum#5]
Sorry, s3_error  file type is not allowed!

We want to add some more types of files to be attached to the task.

**Comment by ajit-orangescrum** [comment]
Hi @karanveersingh001,

This file type is not allowed in our environment and the enhancement is not in our pipeline.

**Comment by karanveersingh001** [comment]
what type of files we can attach with the task.

**Comment by ajit-orangescrum** [comment]
"bat", "com", "cpl", "dll", "exe", "msi", "msp", "pif", "shs", "sys", "cgi", "reg", "bin", "torrent", "yps", "mpg", "dat", "xvid", "scr", "com", "pif", "chm", "cmd", "cpl", "crt", "hlp", "hta", "inf", "ins", "isp", "jse?", "lnk", "mdb", "ms", "pcd", "pif", "scr", "sct", "shs", "vb", "ws", "vbs"

The above files are not allowed. The files excluded from these formats are allowed to be attached to the task.
