### ISSUE TITLE
Icons are not visible to edit task.

### ISSUE THREAD

**Issue by karanveersingh001** [Orangescrum/orangescrum#6]
Icons are not visible to edit tasks.

![image](https://user-images.githubusercontent.com/56407545/169770549-29497a40-9c6d-4c4e-affc-2cb6a89117b4.png)

**Comment by ajit-orangescrum** [comment]
Hi @karanveersingh001, thanks for reaching out to us.

The team has acknowledged and fixed the same issue with [Orangescrum V2.0.6](https://github.com/Orangescrum/orangescrum/releases/tag/V2.06) release.

**Comment by karanveersingh001** [comment]
how to update my version to this version

**Comment by ajit-orangescrum** [comment]
You need to download the latest version from the repository and need to re-install it on your server.

Note: If you re-install the Community edition, make sure to backup your database.

1. Rename the project folder.
2. After fresh installation go-to app/config
3. Replace the file constant.php and database.php from the old project folder.
