### ISSUE TITLE
Profile Image not seen dynamically

### ISSUE THREAD

**Issue by swapnilg** [Orangescrum/orangescrum#63]
The profile image when uploaded does not show up. I digged into it and found that the image is uploaded  but the user/image_thumb is giving an error Source image does not exist! 

(url: http://scrum.fierydevs.com/users/image_thumb/?type=photos&file=e04e3c0a0dcb471169951522335851c5.jpg&sizex=100&sizey=100&quality=100) .

But the image is uploaded and cropped too ! http://scrum.fierydevs.com/users/files/photos/e04e3c0a0dcb471169951522335851c5.jpg

Server:
Ubuntu 14.04
Nginx
PHP-FPM

Reproducing this issue:
1) Login go to Profile 
2) Delete and upload the new profile pic
3) Image link will work but image src doesn't diplay the image.

**Comment by swapnilg** [comment]
if i change from user controller to app controller this works fine !

**Comment by pryspry** [comment]
can you give more details how to resolve this? i'm facing the same issue

**Comment by swapnilg** [comment]
**Pryspry the issue is not yet resolved** 
The identified problem symptoms are:
1) Even if there is an error in application like i delete UsersController the error remains the same.The url always responds to  `Source image does not exist!` *__url caching might be at work but tried disabling the caching with cache as false and debug to 2. __*
2) Changing in above url from user controller to app controller this works fine.Since it altogether embedded in many views cannot just change it. The url which is problematic is `users/image_thumb`  *__explicit configuration only for user controller__*
3) This is interesting -> app/image_thumb transfers it as image/jpeg while users/image_thumb transfers it as image/html. The console says `Resource interpreted as Image but transferred with MIME type text/html ` when url is users/image_thumb.
I have been into digging more into the source code pryspry please give your server configuration also we may fix it soon.

**Comment by swapnilg** [comment]
Fixed !!!

The problem is in line 144 in constants.php in app/Config
Change the line 144 to `$w_root = $_SERVER['DOCUMENT_ROOT'].'/'; `

**Comment by pryspry** [comment]
works for me. thanks :)

**Comment by alexbogo** [comment]
Hi,

Can you please post your nginx server settings file?

**Comment by CbcGroupSis** [comment]
app/Config/constants.php
`$w_root = $_SERVER['DOCUMENT_ROOT'].'/';`
AND 
app/webroot/users/image_thumb/index.php
line 70
`if(file_exists($images_folder.$from_name)){
        $file_path = $images_folder.$from_name;
    }else{
        $file_path = '../../files/photos/'.str_replace(' ','',urldecode($_REQUEST['file']));
}`
