### ISSUE TITLE
Errors when requesting profile images

### ISSUE THREAD

**Issue by timmolter** [Orangescrum/orangescrum#65]
Install so far successful minus this last remaining issue. Any page which show user profiles causes these errors in error.log:

    [Sun May 03 10:21:30.478147 2015] [:error] [pid 8671] [client 5.6.7.8:55532] PHP Notice:  Use of undefined constant WWW_ROOT - assumed 'WWW_ROOT' in /var/www/html/orangescrum-1.5.6/app/Config/constants.php on line 143, referer: http://1.2.3.4:12324/users/profile
    [Sun May 03 10:21:30.478505 2015] [:error] [pid 8671] [client 5.6.7.8:55532] PHP Notice:  Undefined variable: file_mime in /var/www/html/orangescrum-1.5.6/app/webroot/users/image_thumb/ImageComponent.php on line 146, referer: http://1.2.3.4:12324/users/profile
    [Sun May 03 10:21:30.478563 2015] [:error] [pid 8671] [client 5.6.7.8:55532] PHP Fatal error:  Call to undefined function ImageCreateTrueColor() in /var/www/html/orangescrum-1.5.6/app/webroot/users/image_thumb/ImageComponent.php on line 215, referer: http://1.2.3.4:12324/users/profile

Also in the browser developer console:

    GET http://1.2.3.4:1234/users/image_thumb/?type=photos&file=user.png&sizex=28&sizey=28&quality=100 500 (Internal Server Error)

**500 (Internal Server Error)**

Any ideas??

**Comment by khanhicetea** [comment]
Add this code before line ```include("../../../Config/constants.php");``` in file ```app/webroot/users/image_thumb/index.php```

```php
if (!defined('DS')) {
	define('DS', DIRECTORY_SEPARATOR);
}
if (!defined('ROOT')) {
	define('ROOT', $_SERVER['DOCUMENT_ROOT']);
}
if (!defined('APP_DIR')) {
	define('APP_DIR', 'app');
}
if (!defined('WEBROOT_DIR')) {
	define('WEBROOT_DIR', 'webroot');
}
if (!defined('WWW_ROOT')) {
	define('WWW_ROOT', ROOT . DS . APP_DIR . DS . WEBROOT_DIR . DS);
}

define('CAKE_CORE_INCLUDE_PATH', ROOT . DS . 'lib');
include (CAKE_CORE_INCLUDE_PATH . DS . 'Cake' . DS . 'bootstrap.php');
```

I will write new pull request, I think it because the bad architecture of CakePHP :disappointed:

**Comment by timmolter** [comment]
@khanhicetea Thanks for helping! Your fix indeed helped get rid of the first two errors I had. Now I still have two remaining errors in `error.log`:

    [Wed May 13 08:11:06.271131 2015] [:error] [pid 1449] [client xxx] PHP Fatal error:  Call to undefined function ImageCreateTrueColor() in /var/www/html/orangescrum-1.5.6/app/webroot/users/image_thumb/ImageComponent.php on line 215, referer: http://1.2.3.4/users/manage
    [Wed May 13 08:11:06.272078 2015] [:error] [pid 1449] [client xxx] PHP Warning:  file_put_contents(/var/www/html/orangescrum-1.5.6/app/tmp/logs/error.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /var/www/html/orangescrum-1.5.6/lib/Cake/Log/Engine/FileLog.php on line 146, referer: http://1.2.3.4/users/manage

and the same error in Chrome dev console:

    GET http://1.2.3.4:1234/users/image_thumb/?type=photos&file=user.png&sizex=28&sizey=28&quality=100 500 (Internal Server Error)

**Comment by khanhicetea** [comment]
Hi @timmolter ,

First one is error because your server miss the php_gd library for image processing. Solution here : http://stackoverflow.com/questions/4560996/call-to-undefined-function-imagecreatetruecolor-error-in-php-pchart
The second is file system error because folder app/tmp and app/webroot don't have written permission. Try to **chmod** them.

Hope it helps. :smile:

**Comment by timmolter** [comment]
@khanhicetea Thank you so much! I installed `php_gd` with `sudo apt-get install php5-gd` and both errors went away. I already chomd'ed those directories, so that wasn't the problem. Thanks again!
