### ISSUE TITLE
Daily Catch Email not working

### ISSUE THREAD

**Issue by sdhanotiya** [Orangescrum/orangescrum#67]
I have set up daily catch up email but  system is not generation or sending any alert email to all member.
I am using orange scrum community edition latest version and other email notification is working.

http://my domain name/dailyUpdateMail/?to="your email" 

When I am going to above link, It is getting below message.

Running Daily Update Alert...Success 

Auto update daily catch is not working.

**Comment by Orangescrum** [comment]
Hi sdhanotiya,
You have set up a cron for Auto update daily catch up .
Otherwise it will not work.

Please set up a cron for Daily catch up.
Method is dailyUpdateMail in the CronController.php

**Comment by sdhanotiya** [comment]
You mean I need to setup this command on cron job settings on my server

*/15 * * * * php q
/var/www/html/orangescrum/app/webroot/cron_dispatcher.php
/cron/dailyUpdateMail

**Comment by Orangescrum** [comment]
Yes, absolutely right.

**Comment by sdhanotiya** [comment]
*/15 * * * * php q
/var/www/html/orangescrum/app/webroot/cron_dispatcher.php
/cron/dailyUpdateMail 

Instead of above command I am using this command 

*/15* * * * wget -q -O - http://my domain/cron/test_email/?to=email id >/dev/null 2>&1

I got email from this command but when i am going to set dailyupdatemail command  I did not got email. see below
wget -q -O - http://my domian/cron/dailyUpdateMail >/dev/null 2>&1

I have set up daily catch mail. 

One More thing
Can you tell me this are three different command or one command.
*/15 * * * * php q
/var/www/html/orangescrum/app/webroot/cron_dispatcher.php
/cron/dailyUpdateMail

**Comment by Orangescrum** [comment]
One command...
Cheers!

**Comment by sdhanotiya** [comment]
It is working now.
Thanks for support.

**Comment by itzsashi** [comment]
what is q in the cron job, i have set up a cron job for, it is not working for me.. if i remove q, cron jobs runs well,but mails are not coming..

**Comment by xyfix** [comment]
If I setup the OrangeScrum from XAMPP (Windows) does Daily Catch Email will running or not? I believe the cronjob is only for Linux. Is there any possible way to make sure that Daily Catch Email running in Windows environment?
