### ISSUE TITLE
How to use mail service without auth?

### ISSUE THREAD

**Issue by duolcr** [Orangescrum/orangescrum#72]
Hi guys,

I installed orangescrum on a very simple server. On that server, I can send email successfully via mail() function or phpmailer configed as below:

$mail->isSMTP(); 
$mail->Host = 'localhost';
$mail->SMTPAuth = false;
$mail->Username = 'my-account@domain.com';
$mail->Password = ''; 
$mail->SMTPSecure = '';
$mail->Port = 25;

$mail->From = 'my-account@domain.com';
$mail->FromName = 'Web Team';
$mail->addAddress('user@domain.com'); 

I configured orangescrum mail as below, but it doesn't work.
define("SMTP_HOST", "localhost");
define("SMTP_PORT", "25");
define("SMTP_UNAME", "my-account@domain.com");
define("SMTP_PWORD", "");

Could you suggest how to make it work? Thanks a lot

**Comment by fbayer** [comment]
https://github.com/Orangescrum/orangescrum/commit/3ac5132f3c03ec833c9e2413fa1c77d6d3dace4e

**Comment by fbayer** [comment]
I just tried it, but it doesn't work for me. I'm sorry, I thought the ticket I've mentioned is the solution.
It seems like orangescrum needs more than only SMTP_HOST, SMTP_PORT and SMTP_UNAME?!

**Comment by kitkatneko** [comment]
I am not sure if this helps, but somehow I could never get orangescrum to use our inhouse smtp - while  telnet and manually sending email worked. eventually opened an account with sendgrid...

**Comment by ilalaina** [comment]
Instead of blank string I used null and it worked for me without auth : 
`define("SMTP_UNAME", null);
define("SMTP_PWORD", null);`

**Comment by kitkatneko** [comment]
@ilalaina  using null did help the behavior for regular smtp. Thanks.
