### ISSUE TITLE
Page/URL: task-report

### ISSUE THREAD

**Issue by lfluvisotto** [Orangescrum/orangescrum#90]
In the page/URL: task-report

I am receiving this output:

���iw�Ʊ0��:���=�=�c��U�\��h�"���~tp0".����VU/������J, �^���k������x��N}6�&��w��_���aÏ��w=�w�g.��$����,����8˦-��Ypu��G�4q'~��4�(m�ae~�4߷�~�}��k0ba泗/���t�9 L��3��[��]k�N��v�5�X��g��R�u� /Z��=Ȣ�Er���)L�f����yAt� �Q��۞�U37�t�!F�~���~�e:����#/}h�����������w:�]��.����M��A-g�B����+{�P������W��'nrD-x���#m����l�9O�p ��%��.���[1Z���3 �߽ ����~�P�� �����(��l?�#_Upn���D�� PS�M�c93Z?U���Zz$<����s�� `�s:�_yO�It�O�jۣ�{s�ʼy����������M}�c�[�+�6��2{�V��$�x�)���[�nw0twG�ݽ�����z�{���fww8�!������ez2F�0�:s/��pr�`��0s�CPx�p(��i\DN��z���u\�đ��͆!4Z/1r&�y]�P���(��==kj4�.\T��@���Aa������.��]$�l�{d���'l�ș�6��#�@Z�$��G��Y�őh��N�s3W<�̓�NS���'Rj�7��*r��(���l8MZ8)��s>�|��̠\���-h���}@��G��¸��F�b���x�������`[�� (��6�d���8_�g3�O���h"  � ��s'�)���\B8�4�|H�$�L���$�j�_�_;�ㅁ(!�DM��B����0�@�Ň֟<�L@�U�G'X�g��B���GJ�,���L��0 a�� �5S7��'O5���t� �p�³c�xpĞ�g����6�B9��L��ѓ����˿��W���7�s��2��'T����,�rƆO"��X6���HY�w�a�"�aC�,E�P/�^��y9`��S�]�,xO8��a�����(5G��iV���r�QU�^���J���\i �:����XU��N�b��_k�� �Wh�&�_��� I�  �˒V ��B�8�iΥ�𖝸�p��e�cL���I�Mw�W>���P�a�,.n����V��/���nfC�q䆷Y0,� Bl��ɑC���ku��es��5��eG#@��۳.��:+�_�̟@����2bjfR.�fj�WsƩ�t-a�-���8�ֻO�04� ��H�����)N�a���ԏ�Ĵ;bb����P�̵�%���� gi�$�Ph�OȌ_b�ss�0-2ه]/�_5���9��ޜH(@W_o6M�h�$���vo� �FC�q7I8�$��j������g2�7�<��eR#j@YÍl� �\0�G���4�_���zC�U��n07���۰�5��!'>�K���[!u޾Fj���]P{�!V�?bf��D �"�?@[?!U��{��r���těɀ�=`I~FJ�H�;��舗]>���4���))��������"^�Ya��W�F����z�P��I��������]��!\__��|�����RX�� t��E�G����Wx`?���3v6��n!Q�itO]��n@Y=_��4�GES�6xDM�xr.�SUg�V>^p�ٞ���q���gg��ޞf~�Bt�8�gx$H��~��>_��Y�䪘��(�z�K<    .�zX�;��A�ц�k�uJ���z���a��ǽ���ς�����W:����{%�t&�L��.�^C�h{-�� �I��+��YŞҪ5x@�I4:�Y����o���^�7�A<�/$g�A����$�b��9^�w����O�m(��V�eeH,t(�l0>D��ZLX��/�Y�`4���.vRh(_!i�/��i⓶�Ϳ}����+`�M�Ѧ*���~6K"v�������$���?�C�����=|̉��]�� �s���Z�\���ln�H���'��6P˞�� ��B�4��TV�������q˻�i �r�j?�-/�&�C�`TXA�``5�c��{-ve��q+p�i��J��AK�pF׍�7��b������sKk�b��k�~�L� ����À��C���G�Kcz�����Jl�p=Y� -��z�E�����5w���[��:O�t% �,�=��8��rO� ���^�)��z6҅�����T���`���_�oT��ųq��q� �)Y�.�wk�����|�?ef'�.�;/� ��"�=�P��&J�ew�`�F�4T�$^W�_l���_���fC,PE�:����r�F4PH���q�_J��Ƈ�g!��I_���n/���_Hc�J�m�m9(s$4:�:B3�q����^�Q�& b0�� ���w;�x6t�L_�#��qD�X�=�.~D�氿G?n��o37����[�B�_�`1�"ϑ8A�B�����t�ώYP���.�ل�;�M����2��|�#�D�Q,��eH��3��e��!(c��oxlp+C�j0�j��_Q��v ����I�$ƞ"����FhQ\��t�-� �PED���[�nM���>��~`������m�8�4�O� th�Ã�����wk�od@�/������M'aj�'n��Q���o�K6��F��w-�)�/�Yn�Q� �8:�_��,+�%��Z��Z��{����ٍn��_��[�.��̋Ɩ��Y�n��M�זÝZ/����^�p�ղ��&2L�/��e&G�;i#��>,bx�xm H鴋�#(�:��>2k �6�MRd��B�/�ĦkZA� ���$���f+�s��c�8 p-�S��3.%���~x���Ys��w�O���E� �Y���������[lAZUԥR����+��l���rz��G��&��@��9*v� �(L[��li+_zF^6RK�W���E��M��F��k���юڦ�i��M����� �������c�/�o�R�)�2fg���OS k��$N2F��Ɍ=Rc�qL�4˭��*�똟a�����b�W뙚��U=��m����r�5�45�&����FGq>5���6/�#��,�}�rޠ������'��;��#R�>aY��6䃈��`/������|d�� ���K�s�0�#��ӛ�9�u��x�`�د!�@u�N�x��\4$08�7���F���4�_� T6�D�*DQpu����G�yf<9���"���*�Ք�X,ӏ���6��t�����T'� ��w���B�g>�3ߘu�7)����p���:��e�,�����ޙ*����|������4�|K�J�c:��[ yǣMV_@|e]�1��؏���О�$��\q�=�����pLڿ�.W^�րa�7o��?�I��W� ���3 ������)��ɷy����d�Ckcη�(*V��y$s W�Z�X p~2��xuYU�mԼ� l�J�o��|O���sܦ~����<���H�0\ v=�p���{Ŝ��~���Y>�Sp�Q�iD�,{ݝ��)O���� 3������ӑI�{�M�&̍��#����e���}!c��+�����\$�5��2J�)�GO��֢����+GP" ��p�ch�4^�e1K�����d�������#H�h#3��0*T�Tp��I�!�N� c�L��e%z���[� -�$��F_����-t;�5/����p��d��|�:�����cE�\�2� Vq�"��a��&P� ][�   ĸ�.��(��!�Y�6���b����5�0nn4 �|<�ZjZ����V��gfTĂU��Q>����꾭>�S0�]�^���o7 H���&���^��R��Q�X s�� ٟk��8�9�2Ki��Қ�����JsMeg��t{;^������3��s��[n�?�����ޮ���ǚ6zJ���nm�m�l-��"t��އB�}�E|�w���N���WʮYɭ:�{���&���BZQ�iR.��li�&P�7�3�w%�Ǥ9`���W������Zɦ��w��eH"_t:��������-Yn�מB�   T"��E�Yt@�V����������t^�����_�F��;��}�Q�UY����ˉ_\@�"�������'O��.�a�=�qC�0��]�-���_�%��b�>�@ ��n:. �+�vk�`�B�hGi�_�k�B�e�Դ�{���qm#��5S9��0�%���1���:��]��&Ʈ������zE�3���mUP~֔j����+�2�͸�R��G��Za_�����b��Ky:���=���NZy Hw0&�%��LD��y5Q�%���~�7Opj��4Š��'k���-1"ȗ#v�(1E�͆�,NX���:��̍n�1N̵��>�/�&=��m�� �qr_��_�R~��%h�6B�2�g@�l�2�3�xV:5���!��AH�?�������,��)���b��f�(��{N�}�'c�T#`=�c��!��K2 ��ϣI�'���pJI<��6,��뽿�dqƂ���&��� & +�A�n�Z��1�J��:����ʛ\=�Nwnh��W�V^���3�%�a�if%�xrgr5M>��F���d��ᵢ���fU��]�=����b%ݢ)Jg�3��胛˚0{�o����Z�����Cy��]�����s�arK��|*msW8?�'ڦ1y������H9p�e���}w�{�͝����f/����D���jp�����Y��e���O��e�@�|���Z�>!~���/���O&����  ��>�J���oȊ �}��˔ l˼�����;C�#��EVp�m���^�r+:���s�R69��g�h���@�8�������Q��T9�x�<�Ċ�G|�U�Ow �`Z��T��8z)�   �[e�MO���|�J��_���W��j���{��?3��=_+�ᣒ�b�|�!�s�_���#�n_�cN�a<$_ʝ)J�W{P�[�A�+d�K��"z����Nv�P�s`P 2$<IgQ����p���G;ç#��3��v]{kk����~�;��i\N�>U�k�Z��y���ŀ����8����GS����l�-���&X� t(� ^�����nn����h�;�����`�����a������߶mxmnn�m?�ݼ� ����^���W���b��xi_���S    �φ��j;?=�e���\���膄:R-^U����dBuѸĴGb,t�%�������?t��u}5ݎ��yGc�Dkz�����|b�]K���Сr�f�~T�)��y�Y��-�x����`��ƥ��j��H��W��'��K��I�Z{�1�ހ��"8��td@��� �&T/��GC.Y��('y�Bњ��dd���swD:�����°�N�#ՙM��>����i`�_^F�w�e'����{�`Oq���U]���S�1P:�UZ�^� �]a��n�-�����Rg-�Z��������eP�=܇h�q��6�9ZF��Nz��QW�8~x�!�؜x�;�Z� b�5ШIy^+����Vt�Y��zX)�T[�sm���'�p�Rn��Șv�\ڲ�v#2�A�M��4W�ݞ�L��W՛��}�b�x���E����y)�̙A�g����$���CvS��^e��:��a�o(�A%u��T� ZlCq�����{dD��Cu#��т+� ��·����(K�H�B�⸢^�˪Rj����sXt���`.�-^HmဆaZv#Whe���՛?��_N��RO�m�˅����z-��|>�V@���Z���k�m�M�"��=�9�pgUh�M�Zm�>\��͒�\p���P��,�JP���׮�Ȱ����Q*/�u.)����{�=������(�ㄇ��;K�?�������Շ"�o�R �-nk�uF!�xwf��� �^V.۾:�f��^f|����J$�HpP�]_�D�t]�CG|�nsh��x:�.�=���A���T ɲP_E�����3W"˲!s�,�̋iP[ W)Q��jLݩ&a�S����s�^�p,׃<z`�$��^z��n���a�����^��iu6C'T3w&�l���:ѹ��%�`�S��wI��7�h.o_�o���^2��#��A��o����lEeXo3��k ܸ���#���f�D�\W5��&A�<���QO�p���j�FG��Botg�U�����T�Rz�yTr�z���`�>"��ݛ��(jHO�锯5�[ �dġ�a[�e�aC�7�Y�6��|91Z��k��%�|s�Os��&P��E�����ů�V�t:|8c�X�����в^4h�Ig|����!����W�hŴ6_�Śk5�y�������,�쫏Yʽ��]��3F��'\ 5���s�պ����cE�Te����A�f����[,� 1$�i��3t�)ڵ</��\��� ��!�;��9|���!d��?fJ�-����]q]��nm(YKy��}}m:U���N5Go��"$×V��x`M�ӤjS5���L�{�̅$b�e$���C�ϯ�-�Vjm1��c��dI1��Z1��� _�d���`s�V��B@���psAs��K{��ا{���sM�k��YlN�͓_��� %��F�%1�÷�m����g������c�8��4�/��-���Osd�{���>�PާWk����V�?�_ȕ��ok%~ w׳�i������o   ��W⋐~A�������lx܃��Ķ�O��/��05Xq������vƵm�f�{�Sb�Z!�9�l��k���e9����Pe$ �$��g&NRNL,���Z�_����� ���kn ���Җo��ʂ'W���7B�(�����gWA�bf_a����%���MG+A\nd�����(��=��b`�#�/X�@��J�(n�I{��m���4Yj�Z�J'9��[ �� ��7a��uJW�h7<-���&7�+���-�i�n+���\�[���f�R����`}G�����Q,�a"x���\��M�T�0��N,��9�R��P���Kskz��g[�g1��$t��Y���'�0�t�T�cW#L}����~��$��]��-,�������O@�e�3�=��Ӳ�f����t����Ua"`,�`/B��H�Y����q���JRJ`)-��I��v۵����<���v����T�<��SQ}+�E@J �;��eo�C�H�N�0�j���� �B���E%)G�RjR������-Z�}�M�X�����[�I^]���Ujt    =���B���V]ʳɯ]wt�t8�&�X�E��Ǹ�n��N����Q)�B.xv��0f���Eu;�.i���P�az,Z�*��iQp[�u @-�I�k�X�! 6�ބ�n�M�O�����HAXDYXŨ/NIA�Y�u6Y'�k�������)�oH�3r+�E�rk�����G�W�Q��"Q����,�>h�U��DC�+H����B��[W -���ͩ�+�   &;�m�Y��J-O���h6)���.���&�2�I��TNbe}D�_P)�!И��]}dK�#b4�N�R��rdU��T�$&jmz��RK "������lu�f��Գi&_�br�JIa��B���3�x *���&���biZ��|A3Z��w��u�Vi����pO�_��{z*Lj� ��P�Zؙ�T�����:��h*���W�k��d�N��ߎ�j$F�����ae��3K��#�y�͔��LrP�JB`AG�d'(��fYگ}Z��# �;/[�jd_���;m�ɯ�+�I��Z����dA%+��(Zv4�Ҝ�v Wkgt����|!Um!�˦�������/���Q���ỹ'{^]����%����L7B��W�7܋����t�d������y[1�NUǵ���]}��|{_}��P�7_�CG�y�r��8v���_ޝԽ�ԥt���_����3G[�s\���%ot�({����C�#J�K��1_�<\���p�9���$����ׅ�`Pp��`� �W�}�Xl�j�Yb5KF���L����j].��H����ɹ�_�C@�Xe���!7��m�����c(���뗦m/[��૟�["�N���jK����z�ۀ�X˟Kb"Q�_g� �Yi���o|��]=��ʓR����/�ӈ����je�_�"Yd� [r�~�-E�~��a���E.Ia���`v�6r����[�7�&P�x27�63�.���m����q8%$�KI�"%�d�A��a�N�EY�H�ϳ$<�B?l��?�������ɔ���e��Oq�SO(�𳟠�������)��0�O?�7�&nt�{)��O?lu�Ǿ��Z�L?�wh~�)ph��&�]�p�Pf����W0ҿ��E��7�t�ӱ��� f{u��}��ƉX!-� �������m����,����^ZǺM-E��-����*�0 iՑJ�S��[, Og���"�}�H�*�!v�0lV�6<`��$=F��\�_�1����t~Wyn��y�N���jO����rh�8����ҶR��6B�_L!�3E.Jҏg.,�K�w�NJ�/����e1���/8��W�i0]�8M)��7�E�?��X����3�?�{�x�=�3�Y,H����/d� lMZa�HX�����S��OET���F2��S�;�����Z��ġ���ͣ�Ŷ�W+%ˆE������K����Ey��I�I�����,N`��6LH������.�Iy���vCww4���y�����nvw��QW,�Y�8/s����{7v���梆)����'����s� ��;�dP���푷�4������?��.ΉI'�S1Z����LZ����o̧�b���� 2�d.��i�ϣu�A�2�_�������O|�##��&f!�R�sm5�[�&FP��&��d7��>��K�I\���eF�p�6�^�ɳta��æ���#�& 3P�.%�,9�6�e��C�H�������b���lץ���6��R����+��Ri�XY�`c�(�Ũ�s���1���<޷��b�Z)��%� 5���h2u"�)4H^�=m�4X�{��B�'V��]f�u6����S?r&q�;��zS���5Q�Q=S�����Ŗr�����>ȧ)AE6��PS]�v�Rl\�L+��$�Q�ZPƯ�����z��L!b�?S�R��)��J�C-׊��\z����Ϟ��,����D`��گY��o�܉�7��YqJ���᠗�L����Mu���`�*�G���§�9vb�,���A=.���ڀ +  �Ƒ�9O`������y칷��{���{GҘQ=���-9T�"�]��ٺ>�]�M����;��/��+�����g���q�ɷ�,o�6��c�,E��{]��3f�C���i������g�����w2K�xB���� ����˕#�JC_���2Ck�U,�2��"��'�o�/���ڹ�l���ɼ�����>h۬˶�o��l��N���J�^g��a�T1+O]M?��F�:��1�u��Z���R�ϳy�a|dP,UՏ�� ʪ���41��Kq���A|C����!�-� ����-� }CIA?�t�2�(p�7q� X� ��(�p&�P�A���0F��1F�|Ot�{_��}/�M�C��I�@c���qp1n������W��5�Ba�|�fƽs#���^���z-���{��l'�c�m��t�{�����^��&Q�_:vk��ڥ�)$�o)q���٫A��l�'�7���V^2�5������-;N�Y��RJ⇫��i j���������[![��w���=��A��Vg�;5h�%¬|���M�-be�2���uh�����?���GyOc5w`�=X�k�6�O��G&���)�H�Rݝ��K;�8���ػ� i�a�a�ƿ6�M��T��6|����A�i��*=R�/d�2���W�g헽�u���%`�������-y�\* w�఩���^�;�Z����zi���|.o���E,YW�v��Y��0q5C����k��� W�F���� 3�B�JG����|����xB�͖ �-�t2�x'�N�<�W�h��?""2��_���,YO���VW4�pt7q@����Y0m��!�QDn�!��gl��H��>sS�ko3���݌���{l������f�\4���I{n�8�w�HU��h6��`���B+��%��-���/��`ܚ��H��=�Q;:��s�~T7ks�����r��5Ъ�Pv\M4X���撪e/�"�;Sm�~����+��O��v����kE�u�v�A�p��Xm���o$���%g�;�?�Ȫ����3�8�I��|[�ծ�>%{Eᦾï������L;X�����a߽=;o���1���t�������+�BGaA���bXZ�3���XJ�ɥ�=�%O1J]���,���G���=�i]���@�� ��� ��@@�B�2�lC�v�n��5t`��R���o�#��̠�}7��YZ�|�Y��K��k�m>�,s`��[�Q�Mq���GgdL)|2B6���t�fu���>휛ng��]�tk��n_w�N��4�@O��9X�9�������)0XC$I�Ue�IF�yFw �Ub��+b����,�X�K�'�lS��ju�@�7�/���r&��V4������i��ۗ�z��h>���t�,���˵�a�\Ӄ�_ ,MDyc\���7�Hm>�5?=C<�n�M���'�UkG�(���,�id�P�a(f�ƈ�,�s���Ϙ�Gn��Ϩ�=�z[>������c9�6�qr����f�@3k�h�O�,  &�~9�y�F�ڥ)������� ;<��������r�b�X�w��pC?�B�h�TU   ��&���XG1�؏R���7zG[3�g�xd��P����@��w���<���'P�Q�~�C ��O���[D,�>�i]bt�� ��Df<��ba��_E�w:t���Ǜ������D��_��7q�n�U�2y��h]��O���|��ky��g�K��fƗ`\ӣT�!�N�he�;��~�39~���HRkW�=�'^��c���W��jk�_5��X��Vs�o�7����i!��$N��k�(������x��� �j��K >�E������&�@߷졸[B^��8h)�y��0�5�fô�;����=�)m�m:�R���/reܱ?WلF����n0�+�C�� �iM������%|�����s`9X&��i��o�1���CH�B�( _���+l���x́Wn �k��F����G_0\8�>B|��҉����e������S$̧a�Ur!�K����V�dl�GAiXUr���5��)t�Pgf�l�9�E~���gn:x0��@�Ʈm����E��C�c� ���D�|��垞{��e�yS5�m��@ �C�m��S���!n���K��� `��� �I'T��,�j.8b5Rut�>�ia��H?j��!�z.�4���n}�?�B�����"    ��]P)rc'p����UK�`>(3a&3�[D�U>�l{ε���\��\��R���ƝbD��eQ��QX�W?� ���p��M�l�R3�a,8���|��� G�w�� ��z=�����H��S1�h�Vq8���/5�~������G���_21��µ��Q�+f���/W_�v.A���2��M��(B�\��3<,J�܉b��B�iRL�$bY��S��b{3%��n��mL��C�[F��e!9����G��]E�,,�ҝNCග��r��z�'M���5hRV�g�fŻ��cw�p�I��S>0�2S0>F�{Vxwt��,��-�k�� �b�˲�}����`��k���RgY�����T�Xl<֨� ���SL�����5|>� �l�5_3o���67�ːN���#����N��?i�>��L��5�.���z9z�V�j�>C� }��7�d���Aop�L�}����cI����h4jmca ~�����i6�{�k��Á?��l_k}�2�`A�f�C�};Zy_-�ya�V�^�l�}d�1�]�51%�A|���bՓ��x�I3m���ִ�t�v3R�N't��2p^������Р(����v��E��P@�AjFn�+�e}�ڧP��:G��̢�7"�1�� ���K~�Αt�΃�]t�RК����`�j7f4C��]�|���0���R��7�l@���>;A�xЁ/��&�.1�0P"?Qz�p;���-(̨�<�b���o�,s� ���2���Zf�B���D�^��Oj�8�%�`�ո��R��>K�c��X�;�3���r��p��C�m���+9��).�=g��R�VJJ�b�Y�~@��'��w<�L�P��u(�SSZ8tk���67~o����F� n��?M�?�?�6r��)����w��hv�z��'R�T4u�k�%u74�$J��^K�a�`�I'� �M}�AȮ�������+f�D&��Z3��t��ijə\��e�r�V�����+{�٫P�o�Hpk1sk�g�A��}ʖkq�,Sd��i�� ]���S���N��ا ]J���>��������do�z���yk�O?_<����L?�?~ �������/����֋�]^��������y�����O��l5?��e�b_D��9>O���џ���Q�m�����]�z��ϥ����]�ooo�����'M�����ke|h��]���'^����<ʚ�?�Y"�Ei0��� B�}a �������3�F��'��`��Q�J�$5e�O:�l� ;����]`�9�    R�q��z�_K�m��0�ĉ?� �\lߠf�M��Y�[��|Ƚ�Vl�X�p�[�`>@���6��W+E3a+p�'nj�#��Sw��P`�YǤ���1�8-`���9��K<< �t�β���٤��̯����Ӽ��<��<ϙ�п��p�B������"���0�Wf��A|����p����)"kԘc�����)8��o>�Y�������+Y�5�/����J�W�R�>[�KBx���WF2V�Q�W�4��դq�g��zQFsa�d�vܢ�e\ �O~�� ���ո�h��zFq����qY����G��S�~��F�f���0=�37� �� k�v�Q 4f�H|li�ɐ�5��R:�W��6o��V�h_�ɰ�D�M��á��joT;;��l�    �#a�q],�%�BdB~���L��E f��/(@�n��0������q���͢ �m��)jݥ�K�a��"'xߎ�����|֚����+IG���(�A�����S~5/f�L7�3�Y=�e���0^π��7Lc�Vxs2���kq���{�.�[r�@�ϏJ�&��<���1�6/a�s�1�^���O��RwY3Z��5�C��}}�� �3���D��-^�������oߞ�<�dS �qѪ�|}��gU��B�b!.�7������W/�����l��K�&� p���%�^�9/��(8���������?߽��˿�z���+�����!l�����~���0�u�Ћ.��&a͓v�1�]�+��3=��o)������i��hn��$o�̊\h�����=�_o_�.\h�gi|sn�~4�ײ�߱af>�q��Ϳ�Oz�ۖvw�6;!�ă�5�����񽹍#oW����EL��d{nÿi�(�1-t����ӹ=$~�w!ҁa������#OoY˫Yh������g����)��wmt؝��T_l��-oB��y���oΛ��/O�  \�+ޞ�}s����W/�#O^.ə��t��&~�]����������CE^�|��q��}&~i�����>ck��/)�FㇸƑ���i����7|������7�77�����ho�����t������_H�T&|�#��o�5tS�P`йQ�B�=@v(�r��͘�W�՟�߿��'�g����o�9�#���B������~ťKL���->�Nui��������o��߽B@eݳ��/��뺀���&��������s@�-���Z�����6͓��4�j��cډSg'~�c�������D6�A���G�f�mk�'A��ڽ.t�u��V����o�4ԝ�ϝ:�e��Y�Qu�/����i��vL��{D�h6t�uK)d����o'C?���ױ4-�kq����d�}��p}}��xd:�ʰ�N�N���(ŞE_*����N��K���q���?�WZ� @�<�^���eq���E����oιr����� pI{h�M0JO����_<��2V��VM��xGrl�������^����������z%n�8'o���%�ӆ�c��^bu��-��IR4K;7ì��}i���(��H3sp6�ah'5[����V��tJ\y����\��1؁���?�n6ik�O�i�f�ʰ����fs?�7��䠙�E���}�e�n ����]}��-�Ud�H{�[r����=�&!ic�1!��DU��iFg�@� �Mu��d4eVy�W�r`* CՑU�|����Լ과���8T��~y���ؑ%`�A��}����t6H��~b�/�򵷣�f����ޓ'���"��.���l�/Ƿ��P�D�7O$�:���T�$���}�xL`�c*�Ջ�2tJ�b_<_�'[9m٦t%A�^g�|�7�����(�����^T�+l<9r����c"�"�F��°�3�"xdį��Dd3��E �����+m��6�񸞿�{μ.�<0��xZE�4�� 6��[.�(����LU�g]l���vyj(�zST)��D� � O)��8���t���P!�����u�U��\4���7n�7w�s�T0�y`��a�,��M`��05|���*K��W���lm'��z'<�#�-U�c�>؇���܋�nߏq� ��}0��\d����-�f��5�8G�V�=6 p�  z��m����S���݇K�/{)�#�aN]��Jv�Z~���B�.��A�y�������a�K]Xhsgh�x c����'�h��q����^��i5�&������vl�����I��X�

**Comment by Orangescrum** [comment]
Hi lfluvisotto,

Can you please share the full screenshot  of the page?
So that it will be easier for us to fix the issue.

**Comment by lfluvisotto** [comment]
![screenshot from 2015-07-29 18 31 48](https://cloud.githubusercontent.com/assets/535626/8970509/6b48ae6a-3620-11e5-8eb9-a738c1d62baa.png)

Follow the server configuration:

Ubuntu 14.04.2 LTS

nginx/1.4.6

PHP 5.5.9

Zend Engine v2.5.0

MySQL 5.6.16
